msm: camera: Fix msm.h include path.
msm.h is now moved to drivers/media/video/msm
directory.

Fixes following compilation error:
drivers/media/video/msm/server/msm_cam_server.h:20:
fatal error: msm.h: No such file or directory

Change-Id: I3bd478558e2b0f583475809244d33f4d59132ec0
Signed-off-by: Rajeev Kulkarni <krajeev@codeaurora.org>